include: package:flutter_lints/flutter.yaml

analyzer:
  exclude:
    - "**/*.g.dart"
    - "**/*.freezed.dart"

linter:
  rules:
    - always_declare_return_types
    - avoid_unused_constructor_parameters
    - directives_ordering
    - omit_local_variable_types
    - prefer_final_locals
    - prefer_relative_imports
    - prefer_single_quotes
    - require_trailing_commas
    - sized_box_for_whitespace
    - sort_child_properties_last
    - sort_pub_dependencies
    - type_annotate_public_apis
    - unawaited_futures
    - use_named_constants
    - use_super_parameters
