name: flyer_chat_workspace

packages:
  - examples/**
  - packages/**

scripts:
  test:selective:
    run: melos exec --fail-fast -- flutter test --no-pub --coverage
    description: run flutter test for a specific package
    packageFilters:
      dirExists: test
  test:
    run: melos run test:selective --no-select
    description: run flutter test in all packages
  coverage:selective:
    exec: genhtml coverage/lcov.info -o coverage/html
    description: generate coverage for a specific package
    packageFilters:
      dirExists: test
  coverage:
    run: melos run test && melos run coverage:selective --no-select
    description: generate coverage for all packages
  analyze:
    exec: dart analyze --fatal-infos .
    description: run `dart analyze` in all packages
  build:
    exec: dart run build_runner build --delete-conflicting-outputs
    packageFilters:
      dependsOn: build_runner
  format:
    run: dart format --set-exit-if-changed .
    description: run `dart format --set-exit-if-changed .` in all packages
  fix:
    run: dart fix --apply .
    description: run `dart fix --apply .` in all packages
